### PR TITLE
CQ-4308112 - [SiteTemplate] Namespace the theme env vars

### PR DESCRIPTION
**Pull request by jckautzmann**
- prefix env vars:
SITE -> AEM_SITE
URL -> AEM_URL
EXPIRATION -> GIT_HASH_EXPIRATION
HASH -> GIT_HASH

### CODE REVIEW

**Review by vladbailescu — APPROVED** [review]

**Review by bartoszglow — APPROVED** [review]

**Review by basecode — CHANGES_REQUESTED** [review]
Looks all good, I just block until `package.json` references the correct Site Theme Builder version based on https://github.com/adobe/aem-site-theme-builder/pull/8

**Comment by jckautzmann** [comment]
@basecode version updated in https://github.com/adobe/aem-site-template-basic/pull/15/commits/644e3e1667bdcce65368e6fead86d8f4a609efdd

**Comment by bartoszglow** [comment]
There is conflict in `package.json` against main branch as in mean time there was updated of `theme-builder` from `2.0.2` to `2.0.4`. Please resolve the conflict.

**Comment by jckautzmann** [comment]
@bartoszglow 
> Please resolve the conflict.
I just did.

**Review by basecode — APPROVED** [review]

**Pull request merged**
